# Commands to start on workspace startup
tasks:
  - name: Start App Server
    # env vars stored as project environment variable in gitpod
    before: |
      sudo apt-get install git-lfs
      git lfs pull
      echo $FIREBASE_CONFIG_TS_B64 | base64 -d > src/environments/firebaseConfig.ts
    init: yarn install
    # https://www.gitpod.io/blog/gitpodify/#unreachable-localhost-urls
    command: yarn ng serve --host 0.0.0.0 --disable-host-check
  ## Could provide additional task to run in parallel terminal
  # - name: Sync content

# Ports to expose on workspace startup
ports:
  - port: 4200
    onOpen: open-preview
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
vscode:
  extensions:
    - Angular.ng-template
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
