# Deploy to firebase hosting on PR merge
# Specifies deployment target based on branch
# Master -> plh_global
# Deployment/{deployment_name} -> {deployment_name}
name: Deployment Hosting
on:
  push:
    branches:
      - deployment/*
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      # Extract deployment name as the slug of target PR branch via string operators, e.g. /deployment/plh_tz -> plh_tz
      # https://www.linuxjournal.com/article/8919, https://github.com/greenbone/gsa/actions/runs/1277581365/workflow
      - name: Set Environment Deployment
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ];                \
          then echo "DEPLOYMENT_NAME=plh_global" >> $GITHUB_ENV;          \
          else echo "DEPLOYMENT_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV;   \
          fi;
        shell: bash
      - run: |
          echo $GITHUB_REF
          echo $DEPLOYMENT_NAME
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'      
      - name: Populate firebaseConfig.ts
        env:
          FIREBASE_CONFIG_TS: ${{ secrets.FIREBASE_CONFIG_TS }}
        run: echo $FIREBASE_CONFIG_TS > src/environments/firebaseConfig.ts
      - run: yarn install
      - name: Set Scripts Deployment
        run: yarn scripts deployment set $DEPLOYMENT_NAME
      ### Generate and upload sourcemaps ###
      - run: yarn build --source-map=true
      - name: set app version
        run: echo "APP_VERSION=$(echo "$(cat package.json | jq -r '.version')")" >> $GITHUB_ENV
      - name: Upload sourcemaps
        run: |
          npx @sentry/cli releases delete ${DEPLOYMENT_NAME}-${APP_VERSION}
          npx @sentry/cli releases files ${DEPLOYMENT_NAME}-${APP_VERSION} upload-sourcemaps www/
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN}}
          SENTRY_URL: https://app.glitchtip.com/
          SENTRY_ORG: idems
          SENTRY_PROJECT: ${{env.DEPLOYMENT_NAME}}
        continue-on-error: true
      - name: Remove sourcemaps from build
        run: |
          echo $(ls www)
          find . -name "*.map" -type f -delete
          echo $(ls www)
      ###   Deploy  ###
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLH_TEENS_APP1 }}"
          projectId: plh-teens-app1
          # NOTE - deployment target should be set in firebase.json and .firebaserc
          target: "${{env.DEPLOYMENT_NAME}}"
          channelId: live
      # Known issue - success message does not specify correct deployment url
      # Not used anywhere else so assume fine for now (only gh action output incorrect)
      # https://github.com/FirebaseExtended/action-hosting-deploy/issues/126
