# Secrets
# SENTRY_AUTH_TOKEN

# Upload build sourcemaps to 3rd party error monitoring service
# NOTE - likely will merge with deploy code unless can find a tidy way to link

# NOTE - currently only used for debugging as methods are integrated into build scripts
name: Sourcemaps Upload
on: workflow_dispatch
jobs:
  sourcemaps_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set Environment Deployment
        # HACK - pr preview brnach only, should replace before merge
        run: echo "DEPLOYMENT_NAME=plh_global" >> $GITHUB_ENV
        # run: |
        #   if [ "$GITHUB_REF" = "refs/heads/master" ];                \
        #   then echo "DEPLOYMENT_NAME=plh_global" >> $GITHUB_ENV;          \
        #   else echo "DEPLOYMENT_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV;   \
        #   fi;
        shell: bash
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Populate firebaseConfig.ts
        env:
          FIREBASE_CONFIG_TS: ${{ secrets.FIREBASE_CONFIG_TS }}
        run: echo $FIREBASE_CONFIG_TS > src/environments/firebaseConfig.ts
      - run: yarn install
      - name: Set Scripts Deployment
        run: yarn workflow deployment set $DEPLOYMENT_NAME
      ### Generate and upload sourcemaps ###
      - run: yarn build --configuration "production,glitchtip"
      - name: set app version
        run: echo "APP_VERSION=$(echo "$(cat package.json | jq -r '.version')")" >> $GITHUB_ENV
      - name: Upload sourcemaps
        run: |
          npx @sentry/cli releases delete ${DEPLOYMENT_NAME}-${APP_VERSION}
          npx @sentry/cli releases files ${DEPLOYMENT_NAME}-${APP_VERSION} upload-sourcemaps www/
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN}}
          SENTRY_URL: https://app.glitchtip.com/
          SENTRY_ORG: idems
          SENTRY_PROJECT: ${{env.DEPLOYMENT_NAME}}
        continue-on-error: true
      - name: Remove sourcemaps from build
        run: |
          echo $(ls www)
          find . -name "*.map" -type f -delete
          echo $(ls www)
        
# NOTE - if testing locally equivalent commands can also be passed as args
# npx @sentry/cli --url https://app.glitchtip.com login
# npx @sentry/cli --url https://app.glitchtip.com releases list --org idems
